
export  const QuestionTitles = [
  '1) How clear and easy to find are your company mission and values?',
  '2) How consistently do business websites, social media and physical marketing materials align to your mission and values?',
  '3) How effective is your business at using multimedia and other visual tools to show customers who you are and what you do?',
  '4) In your marketplace, how unique is your business concept?',
  '5) Please rate the perception a customer might form when first experiencing your business?',

  '1) How confident are you that consistent, constructive messages are being presented throughout your business?',
  '2) What is your level of Facebook, Twitter, LinkedIn (other online community) activity (for example, to share industry developments, offers and team news)',
  '3) How effective is your business at managing its referral network (in and/or out)?',
  '4) Please describe your business response times when following up on customer enquiries (for example, against a 24hr benchmark)?',
  '5) How well does your business deal with complaints and feedback?',


  '1) When you use physical literature and multimedia tools how consistent is the customer/user experience?',
  '2) How would you rate the overall visual quality and impact of the multimedia tools you use?',
  '3) How effective are you at collecting customer insight to develop information sharing tools?',
  '4) For larger transactions, how is your ability to provide borrower-friendly payment options (for example, leasing or finance)?',
  '5) Please rate how well aligned the style and quality of your business documentation is to your overall concept?',




  '1) When it comes to what your customer really wants, how in-tune is your business?',
  '2) How well do you share customer insights across your business?',
  '3) Assumption can affect what we share and how we share it, please rate how your business manages assumptions?',
  '4) How structured and consistent is your business approach to internal and external communications?',
  '5) How would you rate your business leaders at taking responsibility for effective communication?',




  '1) How skillful is your business at creating a positive impression in the mind of a customer?',
  '2) How important are post-negotiation activities seen to be within your business?',
  '3) How consistent are you as a business when it comes to consolidation (for example, do you all follow the same process)?',
  '4) How well does your business manage the internal negative perceptions of its staff (for example, high product cost or low service quality)?',
  '5) What are the chances your customers will tell their family and friends about you?',
]


export const idustrys = [
  "Accountants",
  "Administration",
  "Advertising",
  "Agriculture",
  "Animal Welfare",
  "Architecture",
  "Audio Visual",
  "Automotive",
  "Aviation",
  "Business Associations",
  "Business Services",
  "Charity",
  "Chemicals",
  "Childcare",
  "Civil Service / Public Office",
  "Communications",
  "Computing",
  "Computing - Games",
  "Computing - Software",
  "Construction",
  "Consulting Services",
  "Consumer Services",
  "Craft",
  "Creative Arts",
  "Data Management",
  "Design",
  "Education",
  "Electronics",
  "Energy",
  "Engineering",
  "Entertainment",
  "Environment",
  "Farming",
  "Financial",
  "Food Production - Sales",
  "Forestry",
  "Furniture",
  "Health - Fitness",
  "Healthcare",
  "Home Maker",
  "Horticulture",
  "Hospitality - café / bars / restaurants",
  "Hotels",
  "HR - Recruitment",
  "Human Rights",
  "Industrial",
  "Internet",
  "IT - Network Services",
  "Legal Services",
  "Logistics",
  "Manufacturing",
  "Marine",
  "Marketing",
  "Mechanical",
  "Media",
  "Medical - Other",
  "Medical Supplies",
  "Military",
  "Mining",
  "Misc Business",
  "Natural Resources",
  "Non-Profits",
  "Office Supplies",
  "Oil - Gas",
  "Pharmaceutical",
  "Philanthropy",
  "Postal, Express Delivery and Couriers",
  "Retail",
  "Retired",
  "Sales",
  "Science",
  "Security",
  "Special Trades / Contractors",
  "Sporting Supplies",
  "Telecom Services - Equipment",
  "Textiles",
  "Tobacco",
  "Tourism",
  "Transportation",
  "Travel",
  "Venture Capital",
  "Veterinary Clinic - Services",
  "Waste Management",
  "Other (pls tell us below)"
]
